/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.BorderLayout;
/**
 *
 * @author iHector Lujan
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     * 
     */
    
    Clientes cliente1 = new Clientes();
    Empleados empleado1 = new Empleados();
    Proveedores proveedor1 = new Proveedores();
    Ventas venta1 = new Ventas();
    Productos producto1 = new Productos();
    
    
    
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        panel1.add(venta1, BorderLayout.CENTER);
        panel2.setVisible(false);
        venta1.setVisible(true);
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        panel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVentas = new Componentes.BotonesAzules();
        btnProductos = new Componentes.BotonesAzules();
        botonesAzules5 = new Componentes.BotonesAzules();
        botonesAzules6 = new Componentes.BotonesAzules();
        botonesAzules7 = new Componentes.BotonesAzules();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonesAzules1 = new Componentes.BotonesAzules();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(218, 217, 217));
        jPanel2.setPreferredSize(new java.awt.Dimension(180, 650));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel2.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel2.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        botonesAzules5.setText("Empleados");
        botonesAzules5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonesAzules5ActionPerformed(evt);
            }
        });
        jPanel2.add(botonesAzules5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        botonesAzules6.setText("Clientes");
        botonesAzules6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonesAzules6ActionPerformed(evt);
            }
        });
        jPanel2.add(botonesAzules6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        botonesAzules7.setText("Proveedores");
        botonesAzules7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonesAzules7ActionPerformed(evt);
            }
        });
        jPanel2.add(botonesAzules7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Boutique: \"Juanita\"");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_shirt-star_532788.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 140));

        botonesAzules1.setText("Compras");
        botonesAzules1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonesAzules1ActionPerformed(evt);
            }
        });
        jPanel2.add(botonesAzules1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        panel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(218, 217, 217));
        jPanel3.setMinimumSize(new java.awt.Dimension(1082, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(1100, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, -1, -1));

        panel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        panel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        panel1.add(panel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonesAzules7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonesAzules7ActionPerformed
        // TODO add your handling code here:

        panel1.add(proveedor1, BorderLayout.CENTER);
        panel2.setVisible(false);

        proveedor1.setVisible(true);
        empleado1.setVisible(false);
        cliente1.setVisible(false);
        venta1.setVisible(false);
        producto1.setVisible(false);
    }//GEN-LAST:event_botonesAzules7ActionPerformed

    private void botonesAzules6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonesAzules6ActionPerformed
        // TODO add your handling code here:

        panel1.add(cliente1, BorderLayout.CENTER);
        panel2.setVisible(false);
        
        venta1.setVisible(false);
        cliente1.setVisible(true);
        empleado1.setVisible(false);
        proveedor1.setVisible(false);
        producto1.setVisible(false);
    }//GEN-LAST:event_botonesAzules6ActionPerformed

    private void botonesAzules5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonesAzules5ActionPerformed
        // TODO add your handling code here:

       panel1.add(empleado1, BorderLayout.CENTER);
        panel2.setVisible(false);

        empleado1.setVisible(true);
        cliente1.setVisible(false);
        proveedor1.setVisible(false);
        venta1.setVisible(false);
        producto1.setVisible(false);
    }//GEN-LAST:event_botonesAzules5ActionPerformed

    private void botonesAzules1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonesAzules1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonesAzules1ActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here
        
        panel1.add(producto1, BorderLayout.CENTER);
        panel2.setVisible(false);

        producto1.setVisible(true);
        empleado1.setVisible(false);
        cliente1.setVisible(false);
        proveedor1.setVisible(false);
        venta1.setVisible(false);
        
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        
         panel1.add(venta1, BorderLayout.CENTER);
        panel2.setVisible(false);
        
        venta1.setVisible(true);
        cliente1.setVisible(false);
        //empleado1.setVisible(false);
        proveedor1.setVisible(false);
        producto1.setVisible(false);
        
    }//GEN-LAST:event_btnVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.BotonesAzules botonesAzules1;
    private Componentes.BotonesAzules botonesAzules5;
    private Componentes.BotonesAzules botonesAzules6;
    private Componentes.BotonesAzules botonesAzules7;
    private Componentes.BotonesAzules btnProductos;
    private Componentes.BotonesAzules btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
